// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Y2OlQMkfVHf-fL4EDOT1X-w7mHoyJvA',
    appId: '1:981237494121:web:18f36b2138ac4cd8494df8',
    messagingSenderId: '981237494121',
    projectId: 'flutter-colab-b16ec',
    authDomain: 'flutter-colab-b16ec.firebaseapp.com',
    storageBucket: 'flutter-colab-b16ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlwIeNPFB6IsFQgFwnPZ6iC1nZu0m-A4',
    appId: '1:981237494121:android:2b2edc24cc0d8b08494df8',
    messagingSenderId: '981237494121',
    projectId: 'flutter-colab-b16ec',
    storageBucket: 'flutter-colab-b16ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ4yLuf7IV3Uo7LF7y6fge30OxKVngSIw',
    appId: '1:981237494121:ios:775b5955a72a4a88494df8',
    messagingSenderId: '981237494121',
    projectId: 'flutter-colab-b16ec',
    storageBucket: 'flutter-colab-b16ec.appspot.com',
    iosClientId: '981237494121-ik7gfr941e9a1qsvlqu0turjl3bidgsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.niongo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ4yLuf7IV3Uo7LF7y6fge30OxKVngSIw',
    appId: '1:981237494121:ios:775b5955a72a4a88494df8',
    messagingSenderId: '981237494121',
    projectId: 'flutter-colab-b16ec',
    storageBucket: 'flutter-colab-b16ec.appspot.com',
    iosClientId: '981237494121-ik7gfr941e9a1qsvlqu0turjl3bidgsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.niongo',
  );
}
